//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Program.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IProgramListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class ProgramBaseListener : IProgramListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProgramParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] ProgramParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProgramParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] ProgramParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProgramParser.dropletname"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDropletname([NotNull] ProgramParser.DropletnameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProgramParser.dropletname"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDropletname([NotNull] ProgramParser.DropletnameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProgramParser.droplettype"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDroplettype([NotNull] ProgramParser.DroplettypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProgramParser.droplettype"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDroplettype([NotNull] ProgramParser.DroplettypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProgramParser.input"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInput([NotNull] ProgramParser.InputContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProgramParser.input"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInput([NotNull] ProgramParser.InputContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProgramParser.output"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOutput([NotNull] ProgramParser.OutputContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProgramParser.output"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOutput([NotNull] ProgramParser.OutputContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProgramParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber([NotNull] ProgramParser.NumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProgramParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber([NotNull] ProgramParser.NumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProgramParser.shape"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShape([NotNull] ProgramParser.ShapeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProgramParser.shape"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShape([NotNull] ProgramParser.ShapeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProgramParser.sensor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSensor([NotNull] ProgramParser.SensorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProgramParser.sensor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSensor([NotNull] ProgramParser.SensorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProgramParser.command"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommand([NotNull] ProgramParser.CommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProgramParser.command"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommand([NotNull] ProgramParser.CommandContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
