//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Program.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class ProgramParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, INPUT=5, OUTPUT=6, WASTE=7, CONTAMINATE=8, 
		MERGE=9, SPLIT=10, MIX=11, TEMP=12, SENSE=13, NEWLINE=14, STRING=15, INT=16;
	public const int
		RULE_program = 0, RULE_dropletname = 1, RULE_droplettype = 2, RULE_number = 3, 
		RULE_shape = 4, RULE_tileentity = 5, RULE_command = 6;
	public static readonly string[] ruleNames = {
		"program", "dropletname", "droplettype", "number", "shape", "tileentity", 
		"command"
	};

	private static readonly string[] _LiteralNames = {
		null, "';'", "'square'", "'circle'", "' '", "'input'", "'output'", "'waste'", 
		"'contam'", "'merge'", "'split'", "'mix'", "'temp'", "'sense'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, "INPUT", "OUTPUT", "WASTE", "CONTAMINATE", 
		"MERGE", "SPLIT", "MIX", "TEMP", "SENSE", "NEWLINE", "STRING", "INT"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Program.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static ProgramParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public ProgramParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public ProgramParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ProgramContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public CommandContext[] command() {
			return GetRuleContexts<CommandContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public CommandContext command(int i) {
			return GetRuleContext<CommandContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] NEWLINE() { return GetTokens(ProgramParser.NEWLINE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NEWLINE(int i) {
			return GetToken(ProgramParser.NEWLINE, i);
		}
		public ProgramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_program; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.EnterProgram(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.ExitProgram(this);
		}
	}

	[RuleVersion(0)]
	public ProgramContext program() {
		ProgramContext _localctx = new ProgramContext(Context, State);
		EnterRule(_localctx, 0, RULE_program);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 20;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,0,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 14;
					command();
					State = 15;
					Match(T__0);
					State = 16;
					Match(NEWLINE);
					}
					} 
				}
				State = 22;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,0,Context);
			}
			State = 23;
			command();
			State = 24;
			Match(T__0);
			State = 26;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==NEWLINE) {
				{
				State = 25;
				Match(NEWLINE);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DropletnameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(ProgramParser.STRING, 0); }
		public DropletnameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_dropletname; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.EnterDropletname(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.ExitDropletname(this);
		}
	}

	[RuleVersion(0)]
	public DropletnameContext dropletname() {
		DropletnameContext _localctx = new DropletnameContext(Context, State);
		EnterRule(_localctx, 2, RULE_dropletname);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 28;
			Match(STRING);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DroplettypeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(ProgramParser.STRING, 0); }
		public DroplettypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_droplettype; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.EnterDroplettype(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.ExitDroplettype(this);
		}
	}

	[RuleVersion(0)]
	public DroplettypeContext droplettype() {
		DroplettypeContext _localctx = new DroplettypeContext(Context, State);
		EnterRule(_localctx, 4, RULE_droplettype);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 30;
			Match(STRING);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NumberContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT() { return GetToken(ProgramParser.INT, 0); }
		public NumberContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_number; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.EnterNumber(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.ExitNumber(this);
		}
	}

	[RuleVersion(0)]
	public NumberContext number() {
		NumberContext _localctx = new NumberContext(Context, State);
		EnterRule(_localctx, 6, RULE_number);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 32;
			Match(INT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ShapeContext : ParserRuleContext {
		public ShapeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_shape; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.EnterShape(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.ExitShape(this);
		}
	}

	[RuleVersion(0)]
	public ShapeContext shape() {
		ShapeContext _localctx = new ShapeContext(Context, State);
		EnterRule(_localctx, 8, RULE_shape);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 34;
			_la = TokenStream.LA(1);
			if ( !(_la==T__1 || _la==T__2) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TileentityContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(ProgramParser.STRING, 0); }
		public TileentityContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_tileentity; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.EnterTileentity(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.ExitTileentity(this);
		}
	}

	[RuleVersion(0)]
	public TileentityContext tileentity() {
		TileentityContext _localctx = new TileentityContext(Context, State);
		EnterRule(_localctx, 10, RULE_tileentity);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 36;
			Match(STRING);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CommandContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INPUT() { return GetToken(ProgramParser.INPUT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public DropletnameContext[] dropletname() {
			return GetRuleContexts<DropletnameContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public DropletnameContext dropletname(int i) {
			return GetRuleContext<DropletnameContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public DroplettypeContext[] droplettype() {
			return GetRuleContexts<DroplettypeContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public DroplettypeContext droplettype(int i) {
			return GetRuleContext<DroplettypeContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public TileentityContext tileentity() {
			return GetRuleContext<TileentityContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberContext[] number() {
			return GetRuleContexts<NumberContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberContext number(int i) {
			return GetRuleContext<NumberContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OUTPUT() { return GetToken(ProgramParser.OUTPUT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WASTE() { return GetToken(ProgramParser.WASTE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CONTAMINATE() { return GetToken(ProgramParser.CONTAMINATE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MERGE() { return GetToken(ProgramParser.MERGE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SPLIT() { return GetToken(ProgramParser.SPLIT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MIX() { return GetToken(ProgramParser.MIX, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ShapeContext shape() {
			return GetRuleContext<ShapeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TEMP() { return GetToken(ProgramParser.TEMP, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SENSE() { return GetToken(ProgramParser.SENSE, 0); }
		public CommandContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_command; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.EnterCommand(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IProgramListener typedListener = listener as IProgramListener;
			if (typedListener != null) typedListener.ExitCommand(this);
		}
	}

	[RuleVersion(0)]
	public CommandContext command() {
		CommandContext _localctx = new CommandContext(Context, State);
		EnterRule(_localctx, 12, RULE_command);
		int _la;
		try {
			State = 135;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case INPUT:
				EnterOuterAlt(_localctx, 1);
				{
				State = 38;
				Match(INPUT);
				State = 39;
				Match(T__3);
				State = 40;
				dropletname();
				State = 41;
				Match(T__3);
				State = 42;
				droplettype();
				State = 43;
				Match(T__3);
				State = 44;
				tileentity();
				State = 45;
				Match(T__3);
				State = 46;
				number();
				}
				break;
			case OUTPUT:
				EnterOuterAlt(_localctx, 2);
				{
				State = 48;
				Match(OUTPUT);
				State = 49;
				Match(T__3);
				State = 50;
				dropletname();
				State = 51;
				Match(T__3);
				State = 52;
				tileentity();
				}
				break;
			case WASTE:
				EnterOuterAlt(_localctx, 3);
				{
				State = 54;
				Match(WASTE);
				State = 55;
				Match(T__3);
				State = 56;
				dropletname();
				}
				break;
			case CONTAMINATE:
				EnterOuterAlt(_localctx, 4);
				{
				State = 57;
				Match(CONTAMINATE);
				State = 58;
				Match(T__3);
				State = 59;
				droplettype();
				State = 64;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__3) {
					{
					{
					State = 60;
					Match(T__3);
					State = 61;
					droplettype();
					}
					}
					State = 66;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
				break;
			case MERGE:
				EnterOuterAlt(_localctx, 5);
				{
				State = 67;
				Match(MERGE);
				State = 68;
				Match(T__3);
				State = 69;
				dropletname();
				State = 70;
				Match(T__3);
				State = 71;
				droplettype();
				State = 72;
				Match(T__3);
				State = 73;
				dropletname();
				State = 74;
				Match(T__3);
				State = 75;
				dropletname();
				State = 80;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__3) {
					{
					{
					State = 76;
					Match(T__3);
					State = 77;
					dropletname();
					}
					}
					State = 82;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
				break;
			case SPLIT:
				EnterOuterAlt(_localctx, 6);
				{
				State = 83;
				Match(SPLIT);
				State = 84;
				Match(T__3);
				State = 85;
				dropletname();
				State = 86;
				Match(T__3);
				State = 87;
				dropletname();
				State = 90;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,4,Context) ) {
				case 1:
					{
					State = 88;
					Match(T__3);
					State = 89;
					number();
					}
					break;
				}
				State = 92;
				Match(T__3);
				State = 93;
				dropletname();
				State = 96;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,5,Context) ) {
				case 1:
					{
					State = 94;
					Match(T__3);
					State = 95;
					number();
					}
					break;
				}
				State = 106;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__3) {
					{
					{
					State = 98;
					Match(T__3);
					State = 99;
					dropletname();
					State = 102;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,6,Context) ) {
					case 1:
						{
						State = 100;
						Match(T__3);
						State = 101;
						number();
						}
						break;
					}
					}
					}
					State = 108;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
				break;
			case MIX:
				EnterOuterAlt(_localctx, 7);
				{
				State = 109;
				Match(MIX);
				State = 110;
				Match(T__3);
				State = 111;
				dropletname();
				State = 112;
				Match(T__3);
				State = 113;
				shape();
				State = 116;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==T__3) {
					{
					State = 114;
					Match(T__3);
					State = 115;
					droplettype();
					}
				}

				}
				break;
			case TEMP:
				EnterOuterAlt(_localctx, 8);
				{
				State = 118;
				Match(TEMP);
				State = 119;
				Match(T__3);
				State = 120;
				dropletname();
				State = 121;
				Match(T__3);
				State = 122;
				tileentity();
				State = 123;
				Match(T__3);
				State = 124;
				number();
				State = 127;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==T__3) {
					{
					State = 125;
					Match(T__3);
					State = 126;
					droplettype();
					}
				}

				}
				break;
			case SENSE:
				EnterOuterAlt(_localctx, 9);
				{
				State = 129;
				Match(SENSE);
				State = 130;
				Match(T__3);
				State = 131;
				dropletname();
				State = 132;
				Match(T__3);
				State = 133;
				tileentity();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static int[] _serializedATN = {
		4,1,16,138,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,1,0,
		1,0,1,0,1,0,5,0,19,8,0,10,0,12,0,22,9,0,1,0,1,0,1,0,3,0,27,8,0,1,1,1,1,
		1,2,1,2,1,3,1,3,1,4,1,4,1,5,1,5,1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,
		6,1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,6,5,6,63,8,6,10,
		6,12,6,66,9,6,1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,6,5,6,79,8,6,10,
		6,12,6,82,9,6,1,6,1,6,1,6,1,6,1,6,1,6,1,6,3,6,91,8,6,1,6,1,6,1,6,1,6,3,
		6,97,8,6,1,6,1,6,1,6,1,6,3,6,103,8,6,5,6,105,8,6,10,6,12,6,108,9,6,1,6,
		1,6,1,6,1,6,1,6,1,6,1,6,3,6,117,8,6,1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,
		6,3,6,128,8,6,1,6,1,6,1,6,1,6,1,6,1,6,3,6,136,8,6,1,6,0,0,7,0,2,4,6,8,
		10,12,0,1,1,0,2,3,148,0,20,1,0,0,0,2,28,1,0,0,0,4,30,1,0,0,0,6,32,1,0,
		0,0,8,34,1,0,0,0,10,36,1,0,0,0,12,135,1,0,0,0,14,15,3,12,6,0,15,16,5,1,
		0,0,16,17,5,14,0,0,17,19,1,0,0,0,18,14,1,0,0,0,19,22,1,0,0,0,20,18,1,0,
		0,0,20,21,1,0,0,0,21,23,1,0,0,0,22,20,1,0,0,0,23,24,3,12,6,0,24,26,5,1,
		0,0,25,27,5,14,0,0,26,25,1,0,0,0,26,27,1,0,0,0,27,1,1,0,0,0,28,29,5,15,
		0,0,29,3,1,0,0,0,30,31,5,15,0,0,31,5,1,0,0,0,32,33,5,16,0,0,33,7,1,0,0,
		0,34,35,7,0,0,0,35,9,1,0,0,0,36,37,5,15,0,0,37,11,1,0,0,0,38,39,5,5,0,
		0,39,40,5,4,0,0,40,41,3,2,1,0,41,42,5,4,0,0,42,43,3,4,2,0,43,44,5,4,0,
		0,44,45,3,10,5,0,45,46,5,4,0,0,46,47,3,6,3,0,47,136,1,0,0,0,48,49,5,6,
		0,0,49,50,5,4,0,0,50,51,3,2,1,0,51,52,5,4,0,0,52,53,3,10,5,0,53,136,1,
		0,0,0,54,55,5,7,0,0,55,56,5,4,0,0,56,136,3,2,1,0,57,58,5,8,0,0,58,59,5,
		4,0,0,59,64,3,4,2,0,60,61,5,4,0,0,61,63,3,4,2,0,62,60,1,0,0,0,63,66,1,
		0,0,0,64,62,1,0,0,0,64,65,1,0,0,0,65,136,1,0,0,0,66,64,1,0,0,0,67,68,5,
		9,0,0,68,69,5,4,0,0,69,70,3,2,1,0,70,71,5,4,0,0,71,72,3,4,2,0,72,73,5,
		4,0,0,73,74,3,2,1,0,74,75,5,4,0,0,75,80,3,2,1,0,76,77,5,4,0,0,77,79,3,
		2,1,0,78,76,1,0,0,0,79,82,1,0,0,0,80,78,1,0,0,0,80,81,1,0,0,0,81,136,1,
		0,0,0,82,80,1,0,0,0,83,84,5,10,0,0,84,85,5,4,0,0,85,86,3,2,1,0,86,87,5,
		4,0,0,87,90,3,2,1,0,88,89,5,4,0,0,89,91,3,6,3,0,90,88,1,0,0,0,90,91,1,
		0,0,0,91,92,1,0,0,0,92,93,5,4,0,0,93,96,3,2,1,0,94,95,5,4,0,0,95,97,3,
		6,3,0,96,94,1,0,0,0,96,97,1,0,0,0,97,106,1,0,0,0,98,99,5,4,0,0,99,102,
		3,2,1,0,100,101,5,4,0,0,101,103,3,6,3,0,102,100,1,0,0,0,102,103,1,0,0,
		0,103,105,1,0,0,0,104,98,1,0,0,0,105,108,1,0,0,0,106,104,1,0,0,0,106,107,
		1,0,0,0,107,136,1,0,0,0,108,106,1,0,0,0,109,110,5,11,0,0,110,111,5,4,0,
		0,111,112,3,2,1,0,112,113,5,4,0,0,113,116,3,8,4,0,114,115,5,4,0,0,115,
		117,3,4,2,0,116,114,1,0,0,0,116,117,1,0,0,0,117,136,1,0,0,0,118,119,5,
		12,0,0,119,120,5,4,0,0,120,121,3,2,1,0,121,122,5,4,0,0,122,123,3,10,5,
		0,123,124,5,4,0,0,124,127,3,6,3,0,125,126,5,4,0,0,126,128,3,4,2,0,127,
		125,1,0,0,0,127,128,1,0,0,0,128,136,1,0,0,0,129,130,5,13,0,0,130,131,5,
		4,0,0,131,132,3,2,1,0,132,133,5,4,0,0,133,134,3,10,5,0,134,136,1,0,0,0,
		135,38,1,0,0,0,135,48,1,0,0,0,135,54,1,0,0,0,135,57,1,0,0,0,135,67,1,0,
		0,0,135,83,1,0,0,0,135,109,1,0,0,0,135,118,1,0,0,0,135,129,1,0,0,0,136,
		13,1,0,0,0,11,20,26,64,80,90,96,102,106,116,127,135
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
